### PR TITLE
Added publicity text to automatically generated README.rst

### PR DESCRIPTION
**Pull request by samredway**
Added some set publicity type text to the bottom of the autogenerated readme as discussed in issue #4

### CODE REVIEW

**Comment by samredway** [comment]
Yes they will definitely work. I must admit I am no expert on ReST syntax myself - but these are anonymous links - I just used them because the strings were a bit longer. I have tested them and actually I think if you click on the commit and then hit the view button it will show you the file rendered. That being said if you feel that it is inconsistent and confusing it is just as easy to use the same named target style links throughout. Definitely agree that it should go at the very top, although I was worried it might look a bit odd above the title. Maybe just in a slightly different sized font or style to the normal paragraph text will help. I'll try it it out in a rst editor with some example text and push an improvement.

**Comment by samredway** [comment]
screen shot 2017-11-07 at 01 14 12
screen shot 2017-11-07 at 01 16 09
screen shot 2017-11-07 at 01 17 13


So here are the options. Sadly we can't really style the links (or I can't find out how to style them) so I don't think styling is the answer. I think we have to just put it in as normal text. From the screenshots personally I think that below the title and above the description is probably best but will hold on pushing. Let me know which you prefer and I can push that version up.

**Comment by freakboy3742** [comment]
I agree: Option 1 looks good. 

I know the styling options are pretty limited - especially when it hits Github. One option that I know *will* work is to make it all bold - `** **` around the outside. Makes it stand out a bit, and Github displayed it reliably.

**Comment by samredway** [comment]
Have done as suggested. You will notice that I have not wrapped the actual links with the bold - this is because you cannot nest links within the styling markup with rst (I know right?). But I think it looks OK - the best way to view it rendered is to click onto the commit and hit the view (view file) button at the top and github will do its thing.

**Comment by freakboy3742** [comment]
Awesome! Thanks for the contribution!

**Pull request merged**
